# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAddcurrencyFt():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addcurrencyFt(self):
    # Test name: add_currencyFt
    # Step # | name | target | value
    # 1 | open | http://34.118.122.203/administration/index.php?controller=AdminLogin&token=1e53b83c6f3b96a3ca75976d5bab155e | 
    self.driver.get("http://34.118.122.203/administration/index.php?controller=AdminLogin&token=1e53b83c6f3b96a3ca75976d5bab155e")
    # 2 | setWindowSize | 1936x1056 |
    self.driver.set_window_size(1936, 1056)
    # 3 | type | id=email | leahivanovici@gmail.com
    self.driver.find_element(By.ID, "email").send_keys("leahivanovici@gmail.com")
    # 4 | type | id=passwd | 123456789
    self.driver.find_element(By.ID, "passwd").send_keys("123456789")
    # 5 | click | css=.ladda-label | 
    self.driver.find_element(By.CSS_SELECTOR, ".ladda-label").click()
    side_bar = WebDriverWait(self.driver, 15).until(lambda d: d.find_element(By.ID, "nav-sidebar"))
    self.driver.execute_script("let container = document.getElementById('nav-sidebar'); container.scrollTo(0,1000);")
    # 6 | click | css=#subtab-AdminInternational span |
    self.driver.find_element(By.CSS_SELECTOR, "#subtab-AdminInternational span").click()
    # 7 | click | linkText=Localization |
    localization = WebDriverWait(self.driver, 15).until(lambda d: d.find_element(By.LINK_TEXT, "Localization"))
    localization.click()
    # 8 | click | id=subtab-AdminCurrencies |
    self.driver.find_element(By.ID, "subtab-AdminCurrencies").click()
    # 9 | click | id=page-header-desc-configuration-add |
    self.driver.find_element(By.ID, "page-header-desc-configuration-add").click()
    # 10 | click | css=.md-checkbox-control |
    checkbox = self.driver.find_element(By.CLASS_NAME, "md-checkbox")
    label = checkbox.find_element(By.TAG_NAME, "label")
    label.click()
    # 11 | click | id=currency_names_1 |
    self.driver.find_element(By.ID, "currency_names_1").click()
    # 12 | type | id=currency_names_1 | Hungarian Forint
    self.driver.find_element(By.ID, "currency_names_1").send_keys("Hungarian Forint")
    # 13 | click | id=currency_iso_code |
    self.driver.find_element(By.ID, "currency_iso_code").click()
    # 14 | type | id=currency_iso_code | Ft
    self.driver.find_element(By.ID, "currency_iso_code").send_keys("Ft")
    # 15 | click | id=currency_exchange_rate |
    self.driver.find_element(By.ID, "currency_exchange_rate").click()
    # 16 | click | css=.number-widget > .col-sm |
    self.driver.find_element(By.CSS_SELECTOR, ".number-widget > .col-sm").click()
    # 17 | type | id=currency_exchange_rate | 376.47
    self.driver.find_element(By.ID, "currency_exchange_rate").send_keys("376.47")
    # 18 | click | id=save-button |
    self.driver.find_element(By.ID, "save-button").click()
    assert "Successful creation." in self.driver.page_source
    # 19 | open | http://34.118.122.203/en/ |
    self.driver.get("http://34.118.122.203/en/")
    # 20 | setWindowSize | 1936x1056 |
    self.driver.set_window_size(1936, 1056)
    # 21 | click | css=.hidden-sm-down:nth-child(2) > .material-icons |
    self.driver.find_element(By.CSS_SELECTOR, ".hidden-sm-down:nth-child(2) > .material-icons").click()
    # 22 | click | linkText=HUF Ft |
    currency_selector = self.driver.find_element(By.CLASS_NAME, "currency-selector")
    dropdown = currency_selector.find_element(By.CLASS_NAME, "dropdown-menu")
    options = dropdown.find_elements(By.TAG_NAME, "a")
    currency = [o.get_attribute("innerText") for o in options]
    assert "Ft" in currency


    ############### Test name: delete_currency ###############
    # Step # | name | target | value
    # 1 | open | http://34.118.122.203/administration/index.php?controller=AdminLogin&token=1e53b83c6f3b96a3ca75976d5bab155e |
    self.driver.get(
      "http://34.118.122.203/administration/index.php?controller=AdminLogin&token=1e53b83c6f3b96a3ca75976d5bab155e")
    # 2 | setWindowSize | 1936x1056 |
    self.driver.set_window_size(1936, 1056)
    # 3 | type | id=email | leahivanovici@gmail.com
    self.driver.find_element(By.ID, "email").send_keys("leahivanovici@gmail.com")
    # 4 | type | id=passwd | 123456789
    self.driver.find_element(By.ID, "passwd").send_keys("123456789")
    # 5 | click | css=.ladda-label |
    self.driver.find_element(By.CSS_SELECTOR, ".ladda-label").click()
    side_bar = WebDriverWait(self.driver, 15).until(lambda d: d.find_element(By.ID, "nav-sidebar"))
    self.driver.execute_script("let container = document.getElementById('nav-sidebar'); container.scrollTo(0,1000);")
    # 6 | click | css=#subtab-AdminInternational span |
    self.driver.find_element(By.CSS_SELECTOR, "#subtab-AdminInternational span").click()
    # 7 | click | linkText=Localization |
    # self.driver.find_element(By.LINK_TEXT, "Localization").click()
    localization = WebDriverWait(self.driver, 15).until(lambda d: d.find_element(By.LINK_TEXT, "Localization"))
    localization.click()
    # 8 | click | id=subtab-AdminCurrencies |
    self.driver.find_element(By.ID, "subtab-AdminCurrencies").click()
    # 9 | click | css=tr:nth-child(3) .md-checkbox-control |
    # self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) .md-checkbox-control").click()
    last_currency = self.driver.find_elements(By.CLASS_NAME, "column-currency_bulk")[-1]
    checkbox = last_currency.find_element(By.CLASS_NAME, "md-checkbox")
    checkbox.click()
    # 10 | click | css=.js-bulk-actions-btn |
    self.driver.find_element(By.CSS_SELECTOR, ".js-bulk-actions-btn").click()
    # 11 | click | id=currency_grid_bulk_action_delete_selection |
    self.driver.find_element(By.ID, "currency_grid_bulk_action_delete_selection").click()
    time.sleep(2)
    # 12 | click | css=.btn-danger |
    self.driver.find_element(By.CSS_SELECTOR, ".btn-danger").click()
    assert "The selection has been successfully deleted." in self.driver.page_source

  
