# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDisplayedpagedelivery():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_displayedpagedelivery(self):
    # Test name: displayed_page_delivery
    # Step # | name | target | value
    # 1 | open | /administration/index.php?controller=AdminLogin&token=1e53b83c6f3b96a3ca75976d5bab155e | 
    self.driver.get("http://34.118.122.203/administration/index.php?controller=AdminLogin&token=1e53b83c6f3b96a3ca75976d5bab155e")
    # 2 | setWindowSize | 1936x1056  |
    self.driver.set_window_size(1936, 1056)
    # 3 | type | id=email | leahivanovici@gmail.com
    self.driver.find_element(By.ID, "email").send_keys("leahivanovici@gmail.com")
    # 4 | type | id=passwd | 123456789
    self.driver.find_element(By.ID, "passwd").send_keys("123456789")
    # 5 | click | id=submit_login | 
    self.driver.find_element(By.ID, "submit_login").click()
    side_bar = WebDriverWait(self.driver, 15).until(lambda d: d.find_element(By.ID, "nav-sidebar"))
    self.driver.execute_script("let container = document.getElementById('nav-sidebar'); container.scrollTo(0,1000);")
    # 6 | click | css=#subtab-AdminParentThemes span |
    self.driver.find_element(By.CSS_SELECTOR, "#subtab-AdminParentThemes span").click()
    # 7 | click | linkText=Pages |
    # self.driver.find_element(By.LINK_TEXT, "Pages").click()
    pages = WebDriverWait(self.driver, 15).until(lambda d: d.find_element(By.LINK_TEXT, "Pages"))
    pages.click()
    # 8 | runScript | window.scrollTo(0,500) |
    self.driver.execute_script("window.scrollTo(0,500)")
    # 9 | click | id=input-false-admin_cms_pages_toggle-1 |
    # self.driver.find_element(By.ID, "input-false-admin_cms_pages_toggle-1").click()
    switch = self.driver.find_element(By.CLASS_NAME, "ps-switch")
    radio = switch.find_element(By.ID, "input-false-admin_cms_pages_toggle-1")
    radio.click()
    assert "The status has been successfully updated." in self.driver.page_source
    # 10 | open | http://34.118.122.203/en/ |
    self.driver.get("http://34.118.122.203/en/")
    # 11 | setWindowSize | 1936x1056 |
    self.driver.set_window_size(1936, 1056)
    # 12 | runScript | window.scrollTo(0,4000) |
    self.driver.execute_script("window.scrollTo(0,4000)")
    time.sleep(2)
    # 13 | click | id=link-cms-page-1-2 |
    self.driver.find_element(By.ID, "link-cms-page-1-2").click()
    assert "The page you are looking for was not found." in self.driver.page_source



    ############### Test name: enable_page_delivery ###############
    # Step # | name | target | value
    # 1 | open | /administration/index.php?controller=AdminLogin&token=1e53b83c6f3b96a3ca75976d5bab155e |
    self.driver.get(
      "http://34.118.122.203/administration/index.php?controller=AdminLogin&token=1e53b83c6f3b96a3ca75976d5bab155e")
    # 2 | setWindowSize | 1936x1056  |
    self.driver.set_window_size(1936, 1056)
    # 3 | type | id=email | leahivanovici@gmail.com
    time.sleep(2)
    self.driver.find_element(By.ID, "email").send_keys("leahivanovici@gmail.com")
    # 4 | type | id=passwd | 123456789
    self.driver.find_element(By.ID, "passwd").send_keys("123456789")
    # 5 | click | id=submit_login |
    self.driver.find_element(By.ID, "submit_login").click()
    side_bar = WebDriverWait(self.driver, 15).until(lambda d: d.find_element(By.ID, "nav-sidebar"))
    self.driver.execute_script("let container = document.getElementById('nav-sidebar'); container.scrollTo(0,1000);")
    # 6 | click | css=#subtab-AdminParentThemes span |
    self.driver.find_element(By.CSS_SELECTOR, "#subtab-AdminParentThemes span").click()
    # 7 | click | linkText=Pages |
    pages = WebDriverWait(self.driver, 15).until(lambda d: d.find_element(By.LINK_TEXT, "Pages"))
    pages.click()
    # 8 | click | id=input-true-admin_cms_pages_toggle-1 |
    self.driver.find_element(By.ID, "input-true-admin_cms_pages_toggle-1").click()
    assert "The status has been successfully updated." in self.driver.page_source





  
